export const LOGIN = 'LOGIN';
export const LOGOUT = 'LOGOUT';

export const SET_CONVERSATIONS = 'SET_CONVERSATIONS';
export const SELECT_CONVERSATION = 'SELECT_CONVERSATION';
export const UPDATE_THREAD = 'UPDATE_THREAD';
export const ADD_MSG_TO_THREAD = 'ADD_MSG_TO_THREAD';
export const DELETE_MESSAGE = 'DELETE_MESSAGE';
export const UPDATE_MESSAGE = 'UPDATE_MESSAGE';
export const STAR_UNSTAR_MESSAGE = 'STAR_UNSTAR_MESSAGE';
export const RESET_CONVERSATIONS_STATE = 'RESET_CONVERSATIONS_STATE';
