export const LOGIN = 'LOGIN';
export const LOGOUT = 'LOGOUT';

export const SET_CONVERSATIONS = 'SET_CONVERSATIONS';
export const SELECT_CONVERSATION = 'SELECT_CONVERSATION';
export const DELETE_MESSAGE = 'DELETE_MESSAGE';
export const DELETE_MESSAGE_FOR_BOTH = 'DELETE_MESSAGE_FOR_BOTH';
export const STAR_MESSAGE = 'STAR_MESSAGE';
